--Creacion de la base de datos
CREATE DATABASE EmpresaAliada;

--Seleccionar base de datos para trabajar en ella
USE EmpresaAliada;
GO

-- Crear las tablas para los datos proporcionados
CREATE TABLE DIM_CATEGORY (
    ID_CATEGORY INT PRIMARY KEY,
    CATEGORY VARCHAR(100)
);

CREATE TABLE DIM_CALENDAR (
    WEEK VARCHAR(10) PRIMARY KEY,
    YEAR INT,
	MONTH INT,
	WEEK_NUMBER INT,
	DATE DATE
);

CREATE TABLE DIM_PRODUCT (
    MANUFACTURER VARCHAR(50),
    BRAND VARCHAR(50),
	ITEM VARCHAR(50),
	ITEM_DESCRIPTION VARCHAR(255),
	CATEGORY INT,
	FORMAT VARCHAR(25),
	ATTR1 VARCHAR(25),
	ATTR2 VARCHAR(25),
	ATTR3 VARCHAR(25)
);

CREATE TABLE DIM_SEGMENT (
	CATEGORY INT,
	ATTR1 VARCHAR(25),
	ATTR2 VARCHAR(25),
	ATTR3 VARCHAR(25),
	FORMAT VARCHAR(25),
	SEGMENT VARCHAR(25)
);

CREATE TABLE FACT_SALES (
	WEEK VARCHAR(10),
	ITEM_CODE VARCHAR(50),
	TOTAL_UNIT_SALE DECIMAL(10, 3),
	TOTAL_VALUE_SALES DECIMAL(10,3),
	TOTAL_UNIT_AVG_WEEKLY_SALES DECIMAL(10,3),
	REGION VARCHAR(50)
);


--Importar los datos en cada tabla utilizando las funciones de importación. 
BULK INSERT DIM_CATEGORY
FROM 'E:\EBAC\Material\Proyecto empresa aliada entregable 1\DIM_CATEGORY (2).csv'
WITH (
    FORMAT = 'CSV',
    FIRSTROW = 2, 
    FIELDTERMINATOR = ',', 
    ROWTERMINATOR = '\n',
    TABLOCK
);

SELECT *
FROM DIM_CATEGORY;

BULK INSERT FACT_SALES
FROM 'E:\EBAC\Material\Proyecto empresa aliada entregable 1\FACT_SALES (1).csv'
WITH (
    FORMAT = 'CSV',
    FIRSTROW = 2,
    FIELDTERMINATOR = ',', 
    ROWTERMINATOR = '\n',
    TABLOCK
);

SELECT *
FROM FACT_SALES;

BULK INSERT DIM_CALENDAR
FROM 'E:\EBAC\Material\Proyecto empresa aliada entregable 1\DIM_CALENDAR (2).csv'
WITH (
    FORMAT = 'CSV',
    FIRSTROW = 2,
    FIELDTERMINATOR = ',', 
    ROWTERMINATOR = '\n',
    TABLOCK
);

SELECT *
FROM DIM_CALENDAR;

BULK INSERT DIM_PRODUCT
FROM 'E:\EBAC\Material\Proyecto empresa aliada entregable 1\DIM_PRODUCT (1).csv'
WITH (
    FORMAT = 'CSV',
    FIRSTROW = 2,
    FIELDTERMINATOR = ',', 
    ROWTERMINATOR = '\n',
    TABLOCK
);

SELECT *
FROM DIM_PRODUCT;

BULK INSERT DIM_SEGMENT
FROM 'E:\EBAC\Material\Proyecto empresa aliada entregable 1\DIM_SEGMENT (1).csv'
WITH (
    FORMAT = 'CSV',
    FIRSTROW = 2,
    FIELDTERMINATOR = ',', 
    ROWTERMINATOR = '\n',
    TABLOCK
);

SELECT *
FROM DIM_SEGMENT;

-- Ejecutar uniones entre las tablas para combinar la información y obtener insights clave sobre las ventas por categoría, región y periodo de tiempo.

SELECT *
FROM DIM_PRODUCT
FULL JOIN DIM_CATEGORY
ON DIM_PRODUCT.CATEGORY = DIM_CATEGORY.ID_CATEGORY
FULL JOIN DIM_SEGMENT
ON DIM_PRODUCT.ATTR1 = DIM_SEGMENT.ATTR1
AND DIM_PRODUCT.ATTR2 = DIM_SEGMENT.ATTR2
AND DIM_PRODUCT.ATTR3 = DIM_SEGMENT.ATTR3

SELECT *
FROM DIM_CALENDAR
FULL JOIN FACT_SALES
ON DIM_CALENDAR.WEEK = FACT_SALES.WEEK

SELECT *
FROM DIM_PRODUCT
FULL JOIN DIM_CATEGORY
ON DIM_PRODUCT.CATEGORY = DIM_CATEGORY.ID_CATEGORY
FULL JOIN DIM_SEGMENT
ON DIM_PRODUCT.ATTR1 = DIM_SEGMENT.ATTR1
AND DIM_PRODUCT.ATTR2 = DIM_SEGMENT.ATTR2
AND DIM_PRODUCT.ATTR3 = DIM_SEGMENT.ATTR3
FULL JOIN FACT_SALES
ON DIM_PRODUCT.ITEM = FACT_SALES.ITEM_CODE
FULL JOIN DIM_CALENDAR
ON DIM_CALENDAR.WEEK = FACT_SALES.WEEK

